### PR TITLE
Sophia compiler improvements

### PR DESCRIPTION
**Pull request by UlfNorell**
This PR contains @rjmh's latest work on the Sophia compiler.

### CODE REVIEW

**Comment by UlfNorell** [comment]
I need this merged for [PT-155506940](https://www.pivotaltracker.com/story/show/155506940).

**Comment by UlfNorell** [comment]
Forgot to run `make dialyzer`.. stay tuned.

**Comment by lucafavatella** [comment]
A line for release notes e.g. as comment in https://github.com/aeternity/epoch/pull/795 would be nice to have.

**Comment by UlfNorell** [comment]
Compiler is still very much work-in-progress, so I'm not sure I'd want anything in the release notes about compiler features until we have them running on chain.

**Pull request merged**
