### PR TITLE
OTP release rename with backward compatible bin/epoch

### PR DESCRIPTION
**Pull request by lucafavatella**
Delivers https://www.pivotaltracker.com/story/show/163191726

Depends on https://github.com/aeternity/epoch/pull/2021
Depends on https://github.com/aeternity/epoch/pull/2024
Depends on https://github.com/aeternity/protocol/pull/291

TODO:
* [x] Ensure https://github.com/aeternity/epoch/pull/2021 merged
* [x] Edit base branch of this PR to master
* [x] Ensure CI passes
* [x] Ensure OSX package job passes - see [auxiliary CI job](https://circleci.com/gh/aeternity/epoch/54411)
* [x] Check how multiple arguments are passed
* [x] Ensure https://github.com/aeternity/epoch/pull/2024 merged
* [ ] Check Windows

### CODE REVIEW

**Comment by lucafavatella** [comment]
@tolbrino Could you test `make ct SUITE=apps/aeutils/test/aeu_keys_gen` on Win please?

**Comment by lucafavatella** [comment]
I added test re handling of multiple args and spaces (keys_gen) for ensuring no regressions in `bin/epoch` script aimed at backward compatibility.

While preparing that, I found this [old comment re spaces](https://github.com/aeternity/epoch/blob/c43a2684e4614302b84eb2ca91b346ab3fd1e3dd/apps/aeutils/priv/extensions/keys_gen.sh#L4) so I [pinged relx upstream on potential change](https://github.com/erlware/relx/pull/682) though including that may not be needed.

**Comment by dincho** [comment]
I found out that `bin/epoch peer_key` (also bin/aeternity peer_key) does not work when node is not running while it was working before.

```
$ bin/aeternity peer_key
{"init terminating in do_boot",{{badmatch,{error,enoent}},[{erl_eval,expr,3,[]}]}}
init terminating in do_boot ({{badmatch,{error,enoent}},[{erl_eval,expr,3,[]}]})

Crash dump is being written to: erl_crash.dump...
done

```

dev1 node (revision: 22bb14a331a9bcddb3be4407310201510b9cb2de):
```
epoch@ip-10-0-1-18:~/node$ bin/epoch peer_key
pp_2qjRvqY5KXQSQJPh65d9KM34YktK9uHfAZT953wafX8NTP51qBepoch@ip-10-0-1-18:~/node$ 
```

Both nodes was not running. If the node is running the command is working as expected.

**Comment by lucafavatella** [comment]
> I found out that `bin/epoch peer_key` (also bin/aeternity peer_key) does not work when node is not running while it was working before.

@dincho I am checking whether this is determined by absence of peer key rather then node not running.

**Comment by lucafavatella** [comment]
@dincho Are you referring to the same behaviour as below? This is master:
```
epoch@ip-10-0-1-104:~/node$ bin/epoch peer_key
pp_dRK8JXRsf8ECv1v2GLWAYsucapYQ1qRyWWiHKm5cSSoAjogeyepoch@ip-10-0-1-104:~/node$
epoch@ip-10-0-1-104:~/node$
epoch@ip-10-0-1-104:~/node$ epmd -names
epmd: up and running on port 4369 with data:
name epoch at port 39808
epoch@ip-10-0-1-104:~/node$ bin/epoch stop
ok
epoch@ip-10-0-1-104:~/node$ bin/epoch peer_key
pp_dRK8JXRsf8ECv1v2GLWAYsucapYQ1qRyWWiHKm5cSSoAjogeyepoch@ip-10-0-1-104:~/node$
epoch@ip-10-0-1-104:~/node$ mv keys/peer_key.pub keys/peer_key.pub.backup
epoch@ip-10-0-1-104:~/node$ mv keys/peer_key keys/peer_key.backup
epoch@ip-10-0-1-104:~/node$ bin/epoch peer_key
{"init terminating in do_boot",{{badmatch,{error,enoent}},[{erl_eval,expr,3,[]}]}}
init terminating in do_boot ({{badmatch,{error,enoent}},[{erl_eval,expr,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
epoch@ip-10-0-1-104:~/node$ cat REVISION
c43a2684e4614302b84eb2ca91b346ab3fd1e3dd
```

**Comment by lucafavatella** [comment]
And I see that when failing the exit code is non-zero:
```
epoch@ip-10-0-1-104:~/node$ bin/epoch peer_key
{"init terminating in do_boot",{{badmatch,{error,enoent}},[{erl_eval,expr,3,[]}]}}
init terminating in do_boot ({{badmatch,{error,enoent}},[{erl_eval,expr,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
epoch@ip-10-0-1-104:~/node$ echo $?
1
```

**Comment by lucafavatella** [comment]
@dincho I tracked ["Make error more user friendly on retrieval of peer key when not done and key not present"](https://www.pivotaltracker.com/story/show/163288027).

**Pull request merged**
