### PR TITLE
PT-161143486: remove ws api

### PR DESCRIPTION
**Pull request by fabiankrol**
pt: https://www.pivotaltracker.com/story/show/161143486
protocol pr: https://github.com/aeternity/protocol/pull/233

things not removed in this pr (post mainnet todos):
- ~~ws domain logic~~ ✅ 
- ~~python ws test~~ ✅
- ~~system_test ws configuration~~ ✅

### CODE REVIEW

**Comment by fabiankrol** [comment]
Hi @z1617 unfortunately currently there are no plans for future websocket api development. I'm afraid you need to use http api

**Comment by tianchaijz** [comment]
> Hi @z1617 unfortunately currently there are no plans for future websocket api development. I'm afraid you need to use http api

Got it, thanks @fabiankrol, close https://github.com/aeternity/epoch/issues/1645

**Comment by z1617** [comment]
> Hi @z1617 unfortunately currently there are no plans for future websocket api development. I'm afraid you need to use http api

Got it, thanks @fabiankrol, close https://github.com/aeternity/epoch/issues/1645

**Comment by dincho** [comment]
Actually I don't see `epoch_config_schema.json` changes, is it intentional? If so, we can postpone the infrastructure changes.

**Comment by sylane** [comment]
All the references to `int_ws` would need to be removed from system tests (`aest_docker.erl` and `aest_nodes.erl`) and from all the system tests configuration files.

**Comment by fabiankrol** [comment]
@dincho i miss the `epoch_config_schema.json` 😓 
Thanks for review i'll update pr

**Comment by fabiankrol** [comment]
@sylane i'm aware of system test cleanup but if it's not crucial i prefer to do this post mainnet. I'll take a look at this once again tho. cc @ThomasArts

**Comment by sylane** [comment]
@fabiankrol Just be sure that the system tests config files still pass the validation.

**Comment by fabiankrol** [comment]
rebased

**Comment by fabiankrol** [comment]
@sylane system test are cleaned up
@dincho docker & config validation are in place

**Comment by fabiankrol** [comment]
@lucafavatella as discussed with @dincho i'm waiting with merging until infrastructure is ready

**Comment by fabiankrol** [comment]
Resolving conflicts via github webtool was a mistake... i'll force push rebased branch

**Comment by fabiankrol** [comment]
By default channel websocket is exposed `/channel` at `127.0.0.1:8044`

**Comment by velzevur** [comment]
@sylane you can check #1667 and aeternity/protocol#244 which aim at clarifying this

**Pull request merged**
