### PR TITLE
Parameterize default max gossip

### PR DESCRIPTION
**Pull request by ThomasArts**
Make gossip parameter configurable
```
sync:
      max_gossip: 10
```

### CODE REVIEW

**Comment by fabiankrol** [comment]
We might want to add parameter to `epoch/apps/aeutils/test/data/epoch_full.yaml`

**Comment by ThomasArts** [comment]
I did not add it to epoch_full.yaml because I don't believe this is something the user should fiddle with. As I posted before, we try to be friendly to other nodes using this variable. It is very likely that some users will see this value and say: let's send it to everyone, then my transactions get everywhere quickly.

We don't want users to put 1000 there. This would potentially break the system as a whole. Therefore, try to minimize use of this variable outside what we believe is a good value.

**Comment by hanssv** [comment]
Single users setting it to 1000 wont make much difference... As long as we don't mention it in the main setup documents we should be fairly safe.

**Comment by fabiankrol** [comment]
@ThomasAerts 👍

**Pull request merged**
