### PR TITLE
Fix deployment template

### PR DESCRIPTION
**Pull request by sylane**

### CODE REVIEW

**Comment by sylane** [comment]
arg, I failed to read the comments before merging...

**Comment by sylane** [comment]
I can confirm the sync > port is used if there is no sync > external_port.

**Comment by sylane** [comment]
@lucafavatella  What kind of confirmation are you talking about ? Do you mean a test ?

**Comment by lucafavatella** [comment]
> @lucafavatella What kind of confirmation are you talking about ? Do you mean a test ?

No, knowledge of the intention of the writer of the code, or code inspection. My question is simply a check.

**Pull request merged**
