### PR TITLE
Plant very early release notes for next release

### PR DESCRIPTION
**Pull request by lucafavatella**
In scope of https://www.pivotaltracker.com/story/show/154920627

### CODE REVIEW

**Comment by lucafavatella** [comment]
Shall split in separate file - one per release - as @sennui mentioned.

**Comment by velzevur** [comment]
Enhaces contract creation API with providing the address of the contract to be created (#800 )

**Comment by lucafavatella** [comment]
Will re-open updated on current master and split in separate file.

**Comment by velzevur** [comment]
(#798) Enriches API by adding functionality for getting a transaction by hash. This works both for transactions already included in a block and still pending ones.

**Pull request closed without merging**
