### PR TITLE
Use canonical serialization for hash.

### LINKED ISSUE #297: Canonical header hashing
Need to base the header hash on the binary representation of the header.

`aec_header:hash_header/1` is basing its hash on the JSON (as a binary) representation of the header. This is dangerous, as the order of the fields in JSON objects is undefined. 

We should base it on the [canonical representation of the block header](https://github.com/aeternity/epoch/wiki/Block-Header) instead.

### PR DESCRIPTION
**Pull request by happi**
Also provide serialization for persistent storage.

Closes #297

### CODE REVIEW

**Comment by happi** [comment]
Some white space errors (tabs) made it in to my commit, I'll fix and update the PR.

**Comment by akorosmezey** [comment]
Is term_to_binary/1 enough here? We may enforce sizes defined in 
https://github.com/aeternity/epoch/wiki/Block-Header
in order to be compatible with other implementations.

**Comment by happi** [comment]
@akorosmezey It is only serialize for store that uses term_to_binary. This is an internal implementation.

The hash is calculated on the binary based on https://github.com/aeternity/epoch/wiki/Block-Header
(Assuming that the hashes in the header has the right sizes, this should perhaps be tested.

**Comment by uwiger** [comment]
It would perhaps have been better to squash the commits first.

**Comment by happi** [comment]
squashed

**Pull request merged**
