### PR TITLE
Fix buggy compilation of _::_ pattern

### PR DESCRIPTION
**Pull request by UlfNorell**

### CODE REVIEW

**Comment by lucafavatella** [comment]
[CI job test failing](https://circleci.com/gh/aeternity/epoch/27652#tests/containers/1) 
```
%%% aeu_requests_SUITE ==> application_test: FAILED
%%% aeu_requests_SUITE ==> {errors_in_lager_log,["13:21:56.995 [error] CRASH REPORT Process <0.1722.1> with 0 neighbours exited with reason: {aborted,{no_exists,aec_chain_state}} in mnesia:wrap_trans/6 line 493\n\n",
                      "13:21:56.996 [error] Supervisor aecore_sup had child aec_tx_pool started with aec_tx_pool:start_link() at undefined exit with reason {aborted,{no_exists,aec_chain_state}} in context start_error\n\n",
                      "13:21:56.996 [error] CRASH REPORT Process <0.1714.1> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,aec_tx_pool,{aborted,{no_exists,aec_chain_state}}}},{aecore_app,start,[normal,[]]}} in application_master:init/4 line 134\n\n"]}
```

> The failing test looks unrelated...

Indeed, restarting.

**Comment by zp-sd** [comment]
@lucafavatella @happi Failing test is tracked in `PT-160014862 Investigate and fix failure during aec_tx_pool start`

**Comment by lucafavatella** [comment]
I tracked this as https://www.pivotaltracker.com/story/show/160021064 so we remember for release notes line if needed.

**Comment by lucafavatella** [comment]
Other failure. May be distinct one, still unrelated. Restarting (and checking this failure).

[CI test job failed](https://circleci.com/gh/aeternity/epoch/27706#tests/containers/1)
```
%%% aecore_txs_SUITE ==> txs_gc: FAILED
%%% aecore_txs_SUITE ==> {{case_clause,4},
 [{aecore_txs_SUITE,txs_gc,1,
                    [{file,"/home/builder/epoch/_build/test/lib/aecore/test/aecore_txs_SUITE.erl"},
                     {line,98}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1546}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1062}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,994}]}]}
```

**Comment by lucafavatella** [comment]
[CI test job failed](https://circleci.com/gh/aeternity/epoch/27728#tests/containers/1):
```
%%% aehttp_integration_SUITE ==> all.internal_endpoints.list_oracle_queries: FAILED
%%% aehttp_integration_SUITE ==> {{badmatch,[]},
 [{aehttp_integration_SUITE,list_oracle_queries,1,
                            [{file,"/home/builder/epoch/_build/test/lib/aehttp/test/aehttp_integration_SUITE.erl"},
                             {line,3904}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1546}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1062}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,994}]}]}
```

**Pull request merged**
