### PR TITLE
PT 159587547 Add contract create compute

### PR DESCRIPTION
**Pull request by rvirding**
[PT-159587547](https://www.pivotaltracker.com/n/projects/2159793/stories/159587547)

Add tx/contract/create/compute call.

### CODE REVIEW

**Comment by rvirding** [comment]
I see it failed the static analysis test but I don't see why. I will try to find the reason and fix it.

**Comment by rvirding** [comment]
I have tried to understand what the problem is but as far as I can see it is complaining that the `apps/aehttp/priv/swagger.json` file has changed, which is not surprising as I have added to `swagger.yaml` and rebuilt the .json file. If this is wrong then please let me know what is the problem and I will fix it.

**Comment by rvirding** [comment]
I also see that I have an error in this branch as the first 2 commits shouldn't be there. Perhaps I should kill this PR and fix up the branch first.

**Comment by lucafavatella** [comment]
> I have tried to understand what the problem is but as far as I can see it is complaining that the apps/aehttp/priv/swagger.json file has changed, which is not surprising as I have added to swagger.yaml and rebuilt the .json file. If this is wrong then please let me know what is the problem and I will fix it.

[Interesting](https://circleci.com/gh/aeternity/epoch/24701). Does `make swagger-check` report same error locally? (I am thinking maybe you locally have a swaggercodegen version that is overloading the one the makefile downloads, or maybe you have a version of Java different from the CI).

**Comment by lucafavatella** [comment]
> I also see that I have an error in this branch as the first 2 commits shouldn't be there. Perhaps I should kill this PR and fix up the branch first. They are good commits but shouldn't be there, they were supposed to be in another branch.

I see this PR needs rebase anyway because of `apps/aehttp/test/aehttp_contracts_SUITE.erl` conflict. I suggest rebasing/selecting commits and force-pushing on this same branch PR (and opening separate PR(s) for commits you feel do not fit focus of this PR).

**Comment by lucafavatella** [comment]
> Does make swagger-check report same error locally?

BTW this is check that CI runs: https://github.com/aeternity/epoch/blob/2db7ecae9f34a91ff7291ea3de265cd2585a1688/.circleci/config.yml#L310

**Comment by lucafavatella** [comment]
> make python-env && make swagger-check

I confirm running locally that I get many errors too. I suggest rebasing on master, re-generating swagger.json and force-pushing.

**Comment by rvirding** [comment]
So I rebased it onto the latest master (last night) and added the changes needed, really only changing the mining calls.

What do you mean by the release notes file?

**Comment by lucafavatella** [comment]
> What do you mean by the release notes file?

[This](https://github.com/aeternity/epoch/blame/dd0da343cd0aa9ab8f4fc23a001430b94775c1ce/docs/release-notes/RELEASE-NOTES-0.20.0.md#L5) file. (I should have been more explicit - apologies.)

Please refer to [past examples](https://github.com/aeternity/epoch/blame/v0.19.0/docs/release-notes/RELEASE-NOTES-0.19.0.md#L5-L20). It is best development practice to update release notes file in same PR that does functional change (even if it sometimes introduces conflicts among concurrent PRs).

**Comment by rvirding** [comment]
OK, added info in release notes file.

**Comment by lucafavatella** [comment]
I took the liberty of marking as WIP - PR in protocol repo needed plus rebase of this PR needed for conflict on release notes.

**Comment by rvirding** [comment]
OK, I will rebase and fix a PR for the protocol.

**Pull request merged**
