### PR TITLE
Relax Swagger check on code lines that are all blank

### PR DESCRIPTION
**Pull request by lucafavatella**
Please refer to commit message for details.

I am considering:
* Whether to restore in place to backed-up code after successful check - in order to avoid leaving working copy with changed files in new lines;
* Deleting the generated files from the repo altogether.

### CODE REVIEW

**Comment by hanssv** [comment]
How can blank lines differ? Is someone running Windows?

**Comment by lucafavatella** [comment]
> How can blank lines differ? Is someone running Windows?

I think it is dependent on number of clauser in function because of Swagger codegen template.

**Comment by lucafavatella** [comment]
`static_analysis` on Circle CI passed. Merging.

**Comment by lucafavatella** [comment]
Merged for fixing CI on master.

> Whether to restore in place to backed-up code after successful check - in order to avoid leaving working copy with changed files in new lines;

This is tracked as https://www.pivotaltracker.com/story/show/155028326

**Pull request merged**
