### PR TITLE
NG rebuild rebased

### PR DESCRIPTION
**Pull request by sennui**
Bitcoin-NG for AE tracked by label: `bitcoin-ng-epic` in pivotal 
Ticket for initial batch of work: closing PT-158722075

Missing in the current change:
- internal representation of micro and key block still is based on the same block record (refactoring next sprint [pivotal](https://www.pivotaltracker.com/story/show/157551442) )
- we don't expose NG specific HTTP API and don't adjust old APIs (next sprint [pivotal](https://www.pivotaltracker.com/story/show/158686045) )
- no Proof of Fraud (next sprint [pivotal](https://www.pivotaltracker.com/story/show/155700135) )
- no Beneficiary in key blocks (next sprint [pivotal](https://www.pivotaltracker.com/story/show/158105016) )
- coinbase value is not accurate (next sprint [pivotal](https://www.pivotaltracker.com/story/show/158105175) )
- HTTP get-block-at-height doesn't behave as it used to - fix ongoing, not a blocker for the release, aepps can ignore
- TX garbage collection is disabled and needs to be adjusted (tracked [pivotal](https://www.pivotaltracker.com/story/show/158688456) )

Known issues: 
- intermittent failure list_oracles test in aehttp suite
- all microblocks go to db backend, we may increase validation and split backends

### CODE REVIEW

**Comment by hanssv** [comment]
I have run (most of) system tests and they are green... Will run all.

**Comment by sennui** [comment]
I have them in loop locally - and they pass. There may be timing issue in CI, tho.

**Comment by lucafavatella** [comment]
Auxiliary CI workflow running Python UAT tests and system tests started as https://circleci.com/workflow-run/c40a22b0-dcca-446e-99ea-333c861ff8b8 (on 04eee9a equivalent to 358b9af5).

**Comment by lucafavatella** [comment]
Auxiliary CI workflow running Python UAT tests started as https://circleci.com/workflow-run/3a02df48-32db-4d28-8189-5bab7b29070b (on cdad667 equivalent to 9a09d588).

**Comment by lucafavatella** [comment]
> P2P doc update in protocol repo beneficial.

I opened https://github.com/aeternity/protocol/pull/136

**Pull request merged**
