### PR TITLE
Trust Circle CI on non-package jobs

### PR DESCRIPTION
**Pull request by lucafavatella**

### CODE REVIEW

**Comment by lucafavatella** [comment]
I see Circle CI ran eunit and static_analysis (failed for concurrent PR fix). I see Circle CI is running test.

I am not seeing how Travis CI behaves (I expect Linux package job, plus async OSX package job).

**Comment by lucafavatella** [comment]
> I am not seeing how Travis CI behaves (I expect Linux package job, plus async OSX package job).

I only see OSX package job.

I pushed attempted workaround cc @dincho

**Comment by dincho** [comment]
> I only see OSX package job.
> 
> I pushed attempted workaround cc @dincho

Strange issue, this workaround will still consume 1 worker job :(

**Comment by lucafavatella** [comment]
> I see Circle CI ran eunit and static_analysis (failed for concurrent PR fix).

I see Travis CI now built package job for both Linux (sync) and OSX (async).

> Strange issue, this workaround will still consume 1 worker job :(

@dincho Though this takes 1 minute only.

**Comment by lucafavatella** [comment]
Finishes https://www.pivotaltracker.com/story/show/155132530

**Pull request merged**
