### PR TITLE
Include mnesia_rocksdb version with fix for backup

### PR DESCRIPTION
**Pull request by lucafavatella**
Finishes https://www.pivotaltracker.com/story/show/155748313

TODO:
* [x] Get https://github.com/aeternity/mnesia_rocksdb/pull/5 merged first
* [x] Update rebar.config/lock to merged https://github.com/aeternity/mnesia_rocksdb/pull/5
* [x] Check that actually `mnesia:backup` works

### CODE REVIEW

**Comment by lucafavatella** [comment]
I see CI (that includes a couple of test suites using DB) passed.

I checked that backup/restore works:
* I started node configured with persisted DB and automining true;
* At height 1, I called `ok = mnesia:backup("/tmp/mnesia.bak").`
* I checked node managed to mine further;
* I stopped node;
* I deleted DB;
* I started node configured with persisted DB but with automining false and without peers;
  * Idea was to start node for restoring DB without allowing DB to be used at the same time. I attempted to use `bin/epoch console_clean` with flag `-pa` for OTP patches and `-pz` for Mnesia ebin, though did not manage to get `mnesia` module loaded probably because embedded release and not in `.boot`.
* I restored DB:
```
(epoch@localhost)1> {atomic, [_|_] = Tabs} = mnesia:restore("/tmp/mnesia.bak", []).
{atomic,[aec_tx,aec_chain_state,aec_blocks,
               aec_account_state,aec_contract_state,aec_block_state,
               aec_oracle_cache,aec_oracle_state,aec_name_service_state,
               aec_name_service_cache,aec_headers]}
```
* I checked chain was at same block height 1 (`aec_chain:top_block_with_state().`);
* I stopped node;
* I started node configured with persisted DB and automining true;
* I quickly checked chain was at same block height 1 (`aec_chain:top_block_with_state().`);
* I checked node managed to mine further.

**Comment by dincho** [comment]
> I checked that backup/restore works:

@lucafavatella is this the procedure you want to be documented ? I mean the general steps:
- disable mining and peers
- start the node
- restore
- stop the node
- enable mining and peers
- start the node

**Comment by lucafavatella** [comment]
> @lucafavatella is this the procedure you want to be documented ? I mean the general steps:

@dincho Yes. I though of writing an automated test for this though it would have taken more time and this functionality is more Dev related than for running node.

**Comment by dincho** [comment]
> @dincho Yes. I thought of writing an automated test for this though it would have taken more time and this functionality is more Dev related than for running node.

I agree, few lines of docs should do.

**Comment by lucafavatella** [comment]
I see CI failure https://circleci.com/gh/lucafavatella/epoch/1085 , I am investigating whether related to this PR.

I suspect https://github.com/aeternity/epoch/blob/9ad96ce5/apps/aecore/src/aec_sync.erl#L474 , combined with [lack of atomicity of writing block to DB and writing chain state (e.g. top block hash) to DB](https://github.com/aeternity/epoch/blob/9ad96ce5/apps/aecore/src/aec_chain_state.erl#L42-L43), to cause one of at least two concurrent syncs of same peer (potentially even same chain from distinct peers) to declare itself as done (`client_done`) without conductor having necessarily updated top block (`aec_chain:top_block/0`).
I have not yet proven it though, so it may still be a lack of guarantee of read-after-Mnesia-transaction-write in Mnesia backend.

**Comment by lucafavatella** [comment]
> I have not yet proven it though, so it may still be a lack of guarantee of read-after-Mnesia-transaction-write in Mnesia backend.

[I now performed further analysis and I have no reason for suspecting guarantees of Mnesia backend](https://www.pivotaltracker.com/story/show/155582602/comments/186931886). This PR is now open for review.

**Pull request merged**
