### PR TITLE
PT-152718992 Validate received block target/difficulty

### PR DESCRIPTION
**Pull request by zp-sd**
* [Finishes #152718992]

### CODE REVIEW

**Comment by lucafavatella** [comment]
@zp-sd Does this need to move the persisted chain to a distinct folder in the environments i.e. similarly to https://github.com/aeternity/epoch/pull/410 ?

**Comment by zp-sd** [comment]
@lucafavatella The block structure will not change, but we will start to recalculate difficulty for every block/header (whereas we are doing this only every `RECALCULATE_DIFFICULTY_FREQUENCY` headers/blocks now). So validation of previously mined blocks may fail.

**Comment by lucafavatella** [comment]
> So validation of previously mined blocks may fail.

Does this affect loading persisted chain?

Anyway - this seems change large enough for starting mining new chain.

**Comment by zp-sd** [comment]
@lucafavatella Agree to start fresh.

@sennui What do you think?

**Pull request merged**
