### PR TITLE
Fix harmless excessive verbosity of Cuckoo executables build

### PR DESCRIPTION
**Pull request by lucafavatella**
Depends on PR #387 (included in this PR).

### CODE REVIEW

**Comment by lucafavatella** [comment]
Force-pushed rebase on master for CI stability.

**Comment by hanssv** [comment]
This is still chatty since it copies all binaries even when nothing has changed... (This amounts to ~40% of all the output when you do make in an up-to-date `epoch`-repo...
I suggest something like this:
```make
$(LIBBLAKE): $(SRC_LIBBLAKE)
	@mkdir -p priv/lib
	cp -p $< $@

$(EXECUTABLES): priv/bin/%: c_src/src/%
	@mkdir -p priv/bin
	cp -p $< $@
```

and removing the the targets `priv/bin` and `priv/lib`... This will make completely silent when nothing is changed, at the sacrifice of doing some unnecessary `mkdir -p`

**Comment by hanssv** [comment]
Last bit of noise (`make[1]: Nothing to be done for 'all'.` can be removed by adding to the `all:` rule:
```
all: $(LIBBLAKE) $(EXECUTABLES)
	@:
```

**Comment by lucafavatella** [comment]
> Let's do it completely silent when nothing has changed!

@hanssv Done in d68992cf (amended, rebased on master, force-pushed).

**Comment by lucafavatella** [comment]
I see CI passed. I see two reviewers approved. Merging.

**Pull request merged**
