### PR TITLE
Smoke test Mnesia index read

### PR DESCRIPTION
**Pull request by lucafavatella**
Finishes https://www.pivotaltracker.com/story/show/154931593

I did not add unit test for Mnesia index read because based on my investigation I would need to set flags in the environment at least for eunit (something like `ERL_FLAGS='-pa ...'`) via the Makefile - hence breaking invocations of eunit not via Makefile. I did not test whether unit tests via CT work.

The test I wanted to add in `aec_db_tests` was:
```
index_test_() ->
    {foreach,
     fun() -> ok = aec_test_utils:start_chain_db() end,
     fun(_) -> ok = aec_test_utils:stop_chain_db() end,
     [{"Read indexes in empty DB",
      fun() ->
              ?assertMatch(Txs when is_list(Txs),
                                    aec_db:transactions_by_account(
                                      <<"FakeAccountPublicKey">>))
      end}]}.
```

----

TODO:
* [x] Manually test that release built by `make prod-build` includes patch;
* [x] Fix Circle CI package smoke test failing on Mnesia patch test (though printing `[]` meaning that patch actually worked);
* [x] Travis still uses pre-20.1 OTP version hence fails - it shall be fixed;
* [ ] Clarify required OTP version i.e. 20.1 (included) - 20.2.2 (included) - preferably by meaningful error when attempting to build OTP patches (e.g. Travis CI has OTP 20.0.x and passed the compilation though failed release generation).
  * The PR could be merged without this item.

### CODE REVIEW

**Comment by lucafavatella** [comment]
> See failure in package job on both [linux](https://travis-ci.org/aeternity/epoch/jobs/337653874#L1733) and [osx](https://travis-ci.org/aeternity/epoch/jobs/337653875#L2945).

@dincho I am not sure why, having opened this PR from a branch in my repo fork, the linux_package job was not run on Circle CI.

**Comment by lucafavatella** [comment]
[eunit on Circle CI](https://circleci.com/gh/lucafavatella/epoch/161) failed for unrelated reason - will attempt to restart it shortly.
```
Pending:
  aec_conductor_tests:miner_test_/0: Run miner for a while
    %% Unknown error: timeout
  undefined
    %% Unknown error: {blame,[10,1,9,1,3,1,1]}
```

**Comment by dincho** [comment]
> UPDATE: It looks like I am unable to restart job on Circle CI cc @dincho

You should go [to the workflow](https://circleci.com/workflow-run/f373fe7f-2786-4e96-ae4b-b42db4770a53) first then you have 2 options: 1. Rerun failed jobs and 2. Rerun the beginning. The second will rerun the full workflow, while most of the time the first one is what you need.

**Comment by dincho** [comment]
> @dincho I am not sure why, having opened this PR from a branch in my repo fork, the linux_package job was not run on Circle CI.

Looks like it has been run now? Or you changed something already?

**Comment by lucafavatella** [comment]
> Looks like it has been run now? Or you changed something already?

I had to push new commits - hence a new build was triggered on Circle CI.

**Comment by lucafavatella** [comment]
I will rebase on master containing #698 - for fixing CI.
I will take the liberty to re-order the commits (and squash the `return` fix in release.py) so not to cause tests to be broken at any point in the history.

**Comment by lucafavatella** [comment]
Apart from:
* Squashing release.py return fix;
* Ordering of commits in order not to break CI/tests in between commits

I amended commit "Prevent OTP patches application failure on OTP 20.2 (Mnesia 4.15.2)" by keeping the [`index_attr()` type change](https://github.com/aeternity/epoch/pull/691/commits/9416641151af07f18c1bcb875aa8b0adc7bbe317#diff-4dc48f607402b211431e00659a07c941L20) as it does not introduce conflict.

**Pull request merged**
