### PR TITLE
Fix compiler bug with builtin map functions

### PR DESCRIPTION
**Pull request by UlfNorell**

### CODE REVIEW

**Comment by happi** [comment]
Could you add the test contract for proof of inclusion that triggered the problem?

**Comment by UlfNorell** [comment]
Test case added

**Comment by UlfNorell** [comment]
Rebased on fixed master.

**Comment by lucafavatella** [comment]
Tracked by https://www.pivotaltracker.com/story/show/159790883

**Comment by lucafavatella** [comment]
Release note line "Fixes compiler bug with builtin map functions" seems good enough. I plan to update PR once other PRs merged.

**Comment by lucafavatella** [comment]
I backed up 99c5258b as branch minor-compiler-bug-bak

**Comment by lucafavatella** [comment]
I added release notes line, rebased, force-pushed.

TODO:
* [ ] After PR #1446 merged, edit target branch to master
* [ ] Squash-and-merge

**Pull request merged**
